/*
    Impact of payment method on feedback sentiment
*/
SELECT t.payment_method,
    COUNT(f.transaction_id) AS feedback_count,
    AVG(f.ratings) AS avg_rating
FROM feedback AS f
JOIN transactions AS t ON f.transaction_id = t.transaction_id
GROUP BY t.payment_method
ORDER BY avg_rating DESC;


/*
    Transaction distribution by payment method.
    This is to find out the payment method that was used the most by customers
    and also to check the revenue generated by each payment method
*/
SELECT payment_method,
    count(*) AS transaction_count,
    SUM(unit_price * quantity) AS total_revenue
FROM transactions
GROUP BY payment_method
ORDER BY total_revenue DESC;