/*  1. How does the payment method impact customer feedback sentiment?
    2. What is the distribution of transactions across different payment methods?
*/

SELECT t.payment_method,
    COUNT(f.transaction_id) AS feedback_count,
    AVG(f.ratings) AS avg_rating
FROM feedback AS f
JOIN transactions AS t ON f.transaction_id = t.transaction_id
GROUP BY t.payment_method
ORDER BY avg_rating DESC;

/*
    Impact of payment method on feedback sentiment.
    This is to provide insight into customer payment preferences.
    After my analysis on this I was able to discover that we do not have much difference on the rate of feedback 
    on all the payment methods as the difference on the averages is not been up to 1.
*/



SELECT payment_method,
    count(*) AS transaction_count,
    SUM(unit_price * quantity) AS total_revenue
FROM transactions
GROUP BY payment_method
ORDER BY total_revenue DESC;

/*
    Transaction distribution by payment method.
    This is to find out the payment method that was used the most by customers
    and also to check the revenue generated by each payment method.
    According to my analysis Credit Card is topping the list which indicates a seamless payment process, so
    it would best to ensure that this option is always available.
*/